# Generated by Django 4.0.4 on 2023-05-23 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dinosaur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "eating_classification",
                    models.CharField(
                        choices=[
                            ("Herbivore", "Herbivore"),
                            ("Omnivore", "Omnivore"),
                            ("Carnivore", "Carnivore"),
                        ],
                        default="Herbivore",
                        max_length=255,
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        choices=[("Brown", "Brown"), ("Green", "Green")],
                        default="Brown",
                        max_length=255,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Triassic", "Triassic"),
                            ("Jurassic", "Jurasic"),
                            ("Cretaceous", "Cretaceous"),
                            ("Paleogene", "Paleogene"),
                            ("Neogene", "Neogene"),
                        ],
                        default="Jurassic",
                        max_length=255,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("T", "Tiny"),
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Very Large"),
                        ],
                        default="M",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="pictures/<django.db.models.fields.related.ForeignKey>/",
                    ),
                ),
                (
                    "dinosaur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dinosaurs.dinosaur",
                        to_field="name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "dinosaurs",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dinosaurs",
                        to="dinosaurs.dinosaur",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
