# Generated by Django 4.0.4 on 2023-05-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dinosaurs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favourite",
            name="dinosaurs",
        ),
        migrations.AddField(
            model_name="dinosaur",
            name="favourites",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="favourite",
                to="dinosaurs.favourite",
            ),
        ),
    ]
