# Generated by Django 4.0.4 on 2023-05-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dinosaurs", "0002_remove_favourite_dinosaurs_dinosaur_favourites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dinosaur",
            name="favourites",
        ),
        migrations.AddField(
            model_name="dinosaur",
            name="favourite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dinosaurs.favourite",
            ),
        ),
    ]
